
spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vhp
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/vhp
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration